### ISSUE TITLE
[BUG] Post login is being redirected to file download component.

### ISSUE THREAD

**Issue by lakshya-20** [code-gambit/VT-WebClient#68]
**Describe the bug**

After successful login, the route is redirected to the file download component.

Area Where Bug Occurred

- [ ] UI/UX
- [X] Business Logic

**How to reproduce the error/bug**
Modify the application routing.

**Before submitting an issue check the below**

- [X] I have synced all my node versions as mentioned in the project"
- [X] I am using the same version of npm as is the project
- [X] My current branch is in sync with the development branch

**Comment by ayush0x00** [comment]
Can you please describe the steps to reproduce the bug?? I am being redirected to `dashboard` after successful login.
